'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
    es: {
        'nav.home': 'Inicio',
        'nav.property': 'La Propiedad',
        'nav.spaces': 'Espacios',
        'nav.experience': 'Experiencia',
        'nav.activities': 'Actividades',
        'nav.book': 'Reservar',
        'hero.title': 'Un refugio natural para desconectarse y reconectar',
        'hero.subtitle': 'Descubre Hacienda La Herrería. Naturaleza, descanso y experiencias auténticas en Silvania.',
        'hero.cta': 'Reservar Ahora',
        'hero.more': 'Conocer Más',
        'slider.slide2.title': 'Arquitectura Tradicional',
        'slider.slide2.subtitle': 'Espacios llenos de historia y confort en armonía con el paisaje.',
        'slider.slide3.title': 'Relajación Absoluta',
        'slider.slide3.subtitle': 'El lugar perfecto para desconectar del ruido y la rutina.',
        'home.intro.welcome': 'Bienvenido',
        'home.intro.title': 'Más que un destino, una pausa necesaria.',
        'home.intro.text': 'Ubicada en Silvania, Vereda Usatama Baja, Cundinamarca, Hacienda La Herrería es un espacio diseñado para el descanso y la contemplación. Una casa tradicional de adobe rodeada de jardines, agua y árboles centenarios te espera para desconectarte del ruido y reconectar con lo esencial.',
        'home.feature.nature': 'Naturaleza',
        'home.feature.nature.desc': 'Más de 10.000 m² de zonas verdes y jardines vivos.',

        'home.feature.rest': 'Descanso',
        'home.feature.rest.desc': 'Espacios pensados para la paz mental.',
        'home.feature.location': 'Ubicación',
        'home.feature.location.desc': 'A solo 5 min de la vía principal.',
        'home.cta.label': 'La Propiedad',
        'home.cta.title': 'Arquitectura con alma',
        'home.cta.text': 'Nuestra casa de adobe conserva la tradición y frescura de la arquitectura campesina, integrando comodidades modernas sin perder su esencia rural. Corredores empedrados y el sonido del agua crean una atmósfera única.',
        'home.cta.button': 'Explorar la propiedad',
        'home.map.title': 'Encuéntranos',
        'login.title': 'Iniciar Sesión',
        'register.title': 'Registrarse',
        // Property Page
        'propiedad.label': 'La Propiedad',
        'propiedad.title': 'Un refugio con historia',
        'propiedad.intro': 'Arquitectura tradicional y naturaleza viva se encuentran en un espacio de más de 10.000 m².',
        'propiedad.house.title': 'La Casa Principal',
        'propiedad.house.text1': 'Construida con técnicas tradicionales en adobe, la casa principal conserva la frescura y el carácter de las antiguas haciendas. Sus muros gruesos y techos altos garantizan una temperatura agradable durante todo el día.',
        'propiedad.house.text2': 'Rodeada de corredores empedrados, invita a sentarse a leer, conversar o simplemente escuchar el sonido del agua que corre por los canales circundantes.',
        'propiedad.location.title': 'Ubicación y Entorno',
        'propiedad.location.text1': 'Ubicada estratégicamente en una zona rural tranquila pero accesible. A solo 10 minutos caminando del casco urbano de Silvania y 5 minutos en vehículo de la vía principal Bogotá–Fusagasugá.',
        'propiedad.location.text2': 'El predio está habitado por árboles centenarios, pavos reales y una variedad de aves que hacen de cada mañana un espectáculo natural.',
        'propiedad.cta.title': 'Ven a conocerla',
        'propiedad.cta.text': 'La Herrería es más que una casa, es una experiencia de desconexión.',
        'propiedad.cta.button': 'Reservar tu estadía',
        // Booking Form
        'booking.title': 'Reserva tu estadía',
        'booking.name': 'Nombre Completo',
        'booking.name.placeholder': 'Tu nombre',
        'booking.email': 'Correo Electrónico',
        'booking.email.placeholder': 'tu@email.com',
        'booking.phone': 'Celular',
        'booking.phone.placeholder': '+57 300...',
        'booking.checkin': 'Check-in',
        'booking.checkout': 'Check-out',
        'booking.guests': 'Huéspedes',
        'booking.submit': 'Consultar Disponibilidad',
        'booking.processing': 'Procesando...',
        'booking.note': 'No se realizará ningún cobro todavía.',
        'booking.summary.night': 'Valor por noche',
        'booking.summary.stay': 'Estadía',
        'booking.summary.total': 'Total Estimado',
        'booking.summary.nights': 'noches',
        'booking.people': 'Personas',
        'booking.room_info.title': 'Información de Habitaciones',
        'booking.room_info.list1': '3 Habitaciones disponibles',
        'booking.room_info.list2': 'Capacidad máx: 4 personas por habitación',
        'booking.room_info.list3': '$400.000 COP por noche/habitación',
        'booking.error.past_dates': 'No es posible reservar fechas pasadas.',
        'booking.camping.alert': 'Capacidad interna completa. Puedes agregar zona de camping.',
        'booking.camping.label': 'Agregar Zona de Camping',
        'booking.event.label': '¿Es un Evento Especial?',
        'booking.event.contact_msg': 'Nuestro equipo se pondrá en contacto contigo para coordinar los detalles.',
        'booking.summary.rooms': 'Habitaciones asignadas',
        'booking.summary.price_per_night_total': 'Precio por noche (Total)',
        'booking.summary.usd_estimate': 'Estimado en USD',
        // Spaces Page
        'spaces.label': 'Nuestros Espacios',
        'spaces.title': 'Un recorrido visual',
        'spaces.intro': 'Cada rincón de La Herrería está pensado para integrarse con el entorno y ofrecer calma.',
        'spaces.item1.title': 'Corredores Empedrados',
        'spaces.item1.desc': 'Espacios de transición que conectan la casa con la naturaleza, ideales para la lectura y el descanso.',
        'spaces.item2.title': 'Jardines y Zonas Verdes',
        'spaces.item2.desc': 'Más de 10.000 m² de áreas verdes cuidadas, hogar de pavos reales y flora nativa.',
        'spaces.item3.title': 'Habitaciones Tradicionales',
        'spaces.item3.desc': 'Espacios sobrios y frescos, diseñados para garantizar un descanso profundo.',
        'spaces.item4.title': 'Canales de Agua',
        'spaces.item4.desc': 'Delicadas corrientes que rodean la casa, proporcionando una banda sonora natural constante.',
        // Reserves Page
        'reserves.label': 'Reservas',
        'reserves.title': 'Planifica tu descanso',
        'reserves.intro': 'Selecciona tus fechas y comprueba la disponibilidad. Todas las reservas se confirman directamente vía E-Mail / WhatsApp.',
        'reserves.info.title': 'Información Importante',
        'reserves.info.checkin': 'Check-in: 3:00 PM | Check-out: 12:00 PM',
        'reserves.info.capacity': 'Capacidad en habitaciones: 12 personas (+ opción camping)',
        'reserves.info.pet': 'Pet friendly (con previo aviso)',
        'reserves.info.party': 'No se permiten fiestas ruidosas',
        'reserves.questions.title': '¿Dudas?',
        'reserves.questions.text': 'Si tienes preguntas específicas o requerimientos especiales, escríbenos directamente.',
        'reserves.questions.chat': 'Chat por WhatsApp',
        // Footer
        'footer.desc': 'Un refugio natural para desconectarse y reconectar. Ubicado en Silvania, Vereda Usatama Baja, Cundinamarca, donde la naturaleza y el descanso se encuentran.',
        'footer.nav.title': 'Navegación',
        'footer.contact.title': 'Contacto',
        'footer.rights': 'Hacienda La Herrería. Todos los derechos reservados.',
        'footer.privacy': 'Política de Privacidad',
        'footer.cookies': 'Política de Cookies',
        'footer.terms': 'Términos y Condiciones',
        'booking.policy_agree': 'Acepto la Política de Privacidad y el tratamiento de mis datos personales',
        // Auth
        'auth.login.title': 'Iniciar Sesión',
        'auth.login.noaccount': '¿No tienes cuenta?',
        'auth.login.register': 'Regístrate aquí',
        'auth.email': 'Correo electrónico',
        'auth.email.placeholder': 'Correo electrónico',
        'auth.password': 'Contraseña',
        'auth.password.placeholder': 'Contraseña',
        'auth.submit.login': 'Entrar',
        'auth.register.title': 'Crear Cuenta',
        'auth.register.hasaccount': '¿Ya tienes cuenta?',
        'auth.register.login': 'Inicia sesión',
        'auth.name': 'Nombre Completo',
        'auth.name.placeholder': 'Nombre Completo',
        'auth.submit.register': 'Registrarse',
        // Password Recovery
        'auth.forgot': '¿Olvidaste tu contraseña?',
        'auth.recover.title': 'Recuperar Contraseña',
        'auth.recover.desc': 'Ingresa tu correo para recibir un enlace de recuperación.',
        'auth.recover.submit': 'Enviar Enlace',
        'auth.recover.success': 'Revisa tu correo para el enlace de recuperación.',
        'auth.recover.back': 'Volver al Inicio de Sesión',
        'auth.update.title': 'Actualizar Contraseña',
        'auth.update.submit': 'Actualizar Contraseña',
        'auth.update.success': 'Contraseña actualizada exitosamente.',
        // Navbar Auth
        'nav.welcome': 'Bienvenido',
        'nav.logout': 'Cerrar Sesión',
        // Experience Page
        'experience.label': 'La Experiencia',
        'experience.title': 'Un refugio de bienestar',
        'experience.intro': 'Hemos diseñado cada aspecto de tu estadía para garantizar privacidad, seguridad y tranquilidad.',
        'experience.philosophy.title': 'Filosofía de descanso',
        'experience.philosophy.text': 'La Herrería es el lugar ideal para desconectarte y vibrar en armonía con la naturaleza. Aquí disfrutas plenamente de su conexión profunda con los elementos —tierra fértil, aguas cristalinas, vientos suaves y fuego vital— mientras compartes energía con caballos y gatos curiosos, recargándote de paz y vitalidad natural.',
        'experience.noise.title': 'Cero Ruido',
        'experience.noise.desc': 'Ambiente libre de parlantes y música alta.',
        'experience.privacy.title': 'Privacidad Total',
        'experience.privacy.desc': 'Acceso exclusivo para huéspedes registrados.',
        'experience.service.title': 'Atención Personalizada',
        'experience.service.text': 'Nuestro anfitrión vive en un área independiente dentro de la propiedad, asegurando una presencia discreta pero disponible para cualquier necesidad que puedas tener.',
        'experience.service.list1': 'Recepción y bienvenida personalizada',
        'experience.service.list2': 'Asistencia con fogatas y chimeneas',
        'experience.service.list3': 'Recomendaciones locales',
        'experience.notes.title': 'Notas para tu visita',
        'experience.notes.list2': 'No acceso a sótanos o áreas de servicio restringidas.',
        'experience.notes.list3': 'Se requiere registro previo de todos los acompañantes.',
        'experience.notes.list4': 'Mascotas bienvenidas previo registro.',
        // Activities Page
        'activities.label': 'Qué hacer',
        'activities.title': 'Actividades y Entorno',
        'activities.intro': 'Desde la contemplación tranquila hasta la aventura activa, La Herrería ofrece opciones para todos.',
        'activities.item1.title': 'Caminatas Ecológicas',
        'activities.item1.desc': 'Recorre senderos naturales dentro y fuera de la hacienda. Descubre la flora local y respira aire puro.',
        'activities.item2.title': 'Ciclismo de Montaña',
        'activities.item2.desc': 'Rutas desafiantes y paisajísticas para los amantes del MTB en los alrededores de Silvania.',
        'activities.item3.title': 'Zonas de BBQ',
        'activities.item3.desc': 'Espacios dispuestos para compartir un asado en familia rodeados de naturaleza.',
        'activities.item4.title': 'Eventos Privados',
        'activities.item4.desc': 'El escenario perfecto para reuniones familiares, retiros pequeños o celebraciones íntimas.',
        'activities.item5.title': 'Camping',
        'activities.item5.desc': 'Zona habilitada para acampar bajo las estrellas rodeado de naturaleza segura.',
        'activities.item6.title': 'Cancha de fútbol 5 (grama natural)',
        'activities.item6.desc': 'Espacio deportivo en grama natural para disfrutar con amigos y familia.',
        'activities.item7.title': 'Tejo',
        'activities.item7.desc': 'Canchas para jugar el deporte tradicional colombiano, ideal para grupos.',
        'activities.item8.title': 'Rana',
        'activities.item8.desc': 'Juego de sapo (rana) disponible para entretenimiento y competencia sana.',
        'activities.cta.title': '¿Listo para vivir la experiencia?',
        'activities.cta.text': 'Reserva ahora y asegura tu espacio en este refugio natural.',
        'activities.cta.button': 'Consultar Disponibilidad',
    },
    en: {
        'nav.home': 'Home',
        'nav.property': 'The Property',
        'nav.spaces': 'Spaces',
        'nav.experience': 'Experience',
        'nav.activities': 'Activities',
        'nav.book': 'Book Now',
        'hero.title': 'A natural refuge to disconnect and reconnect',
        'hero.subtitle': 'Discover Hacienda La Herrería. Nature, rest, and authentic experiences in Silvania.',
        'hero.cta': 'Book Now',
        'hero.more': 'Learn More',
        'slider.slide2.title': 'Traditional Architecture',
        'slider.slide2.subtitle': 'Spaces full of history and comfort in harmony with the landscape.',
        'slider.slide3.title': 'Absolute Relaxation',
        'slider.slide3.subtitle': 'The perfect place to disconnect from noise and routine.',
        'home.intro.welcome': 'Welcome',
        'home.intro.title': 'More than a destination, a necessary pause.',
        'home.intro.text': 'Located in Silvania, Vereda Usatama Baja, Cundinamarca, Hacienda La Herrería is a space designed for rest and contemplation. A traditional adobe house surrounded by gardens, water, and century-old trees awaits you to disconnect from the noise and reconnect with the essential.',
        'home.feature.nature': 'Nature',
        'home.feature.nature.desc': 'More than 10,000 m² of green areas and living gardens.',
        'home.feature.rest': 'Rest',
        'home.feature.rest.desc': 'Spaces designed for mental peace.',
        'home.feature.location': 'Location',
        'home.feature.location.desc': 'Just 5 min from the main road.',
        'home.cta.label': 'The Property',
        'home.cta.title': 'Architecture with Soul',
        'home.cta.text': 'Our adobe house preserves the tradition and freshness of rural architecture, integrating modern comforts without losing its rural essence. Cobbled corridors and the sound of water create a unique atmosphere.',
        'home.cta.button': 'Explore the property',
        'home.map.title': 'Find Us',
        'login.title': 'Log In',
        'register.title': 'Sign Up',
        // Property Page
        'propiedad.label': 'The Property',
        'propiedad.title': 'A refuge with history',
        'propiedad.intro': 'Traditional architecture and living nature meet in a space of more than 10,000 m².',
        'propiedad.house.title': 'The Main House',
        'propiedad.house.text1': 'Built with traditional adobe techniques, the main house preserves the freshness and character of ancient haciendas. Its thick walls and high ceilings guarantee a pleasant temperature all day.',
        'propiedad.house.text2': 'Surrounded by cobbled corridors, it invites you to sit and read, talk, or simply listen to the sound of water running through the surrounding channels.',
        'propiedad.location.title': 'Location and Surroundings',
        'propiedad.location.text1': 'Strategically located in a quiet but accessible rural area. Just 10 minutes walking from the urban center of Silvania and 5 minutes by vehicle from the main Bogotá–Fusagasugá road.',
        'propiedad.location.text2': 'The property is inhabited by century-old trees, peacocks, and a variety of birds that make every morning a natural spectacle.',
        'propiedad.cta.title': 'Come see it',
        'propiedad.cta.text': 'La Herrería is more than a house, it is a disconnection experience.',
        'propiedad.cta.button': 'Book your stay',
        // Booking Form
        'booking.title': 'Book your stay',
        'booking.name': 'Full Name',
        'booking.name.placeholder': 'Your name',
        'booking.email': 'Email',
        'booking.email.placeholder': 'you@email.com',
        'booking.phone': 'Phone',
        'booking.phone.placeholder': '+57 300...',
        'booking.checkin': 'Check-in',
        'booking.checkout': 'Check-out',
        'booking.guests': 'Guests',
        'booking.submit': 'Check Availability',
        'booking.processing': 'Processing...',
        'booking.note': 'No charges will be made yet.',
        'booking.summary.night': 'Price per night',
        'booking.summary.stay': 'Stay',
        'booking.summary.total': 'Estimated Total',
        'booking.summary.nights': 'nights',
        'booking.people': 'People',
        'booking.room_info.title': 'Room Information',
        'booking.room_info.list1': '3 Rooms available',
        'booking.room_info.list2': 'Max capacity: 4 people per room',
        'booking.room_info.list3': '$400,000 COP per night/room',
        'booking.error.past_dates': 'Past dates cannot be selected.',
        'booking.camping.alert': 'Internal capacity full. You may add camping area.',
        'booking.camping.label': 'Add Camping Area',
        'booking.event.label': 'Is this a Special Event?',
        'booking.event.contact_msg': 'Our team will contact you shortly to coordinate details.',
        'booking.summary.rooms': 'Rooms assigned',
        'booking.summary.price_per_night_total': 'Price per night (Total)',
        'booking.summary.usd_estimate': 'Estimated in USD',
        // Spaces Page
        'spaces.label': 'Our Spaces',
        'spaces.title': 'A visual tour',
        'spaces.intro': 'Every corner of La Herrería is designed to integrate with the environment and offer calm.',
        'spaces.item1.title': 'Cobbled Corridors',
        'spaces.item1.desc': 'Transition spaces connecting the house with nature, ideal for reading and resting.',
        'spaces.item2.title': 'Gardens and Green Areas',
        'spaces.item2.desc': 'More than 10,000 m² of cared green areas, home to peacocks and native flora.',
        'spaces.item3.title': 'Traditional Rooms',
        'spaces.item3.desc': 'Sober and fresh spaces, designed to guarantee deep rest.',
        'spaces.item4.title': 'Water Channels',
        'spaces.item4.desc': 'Delicate streams surrounding the house, providing a constant natural soundtrack.',
        // Reserves Page
        'reserves.label': 'Reserves',
        'reserves.title': 'Plan your rest',
        'reserves.intro': 'Select your dates and check availability. All reservations are confirmed directly via Email / WhatsApp.',
        'reserves.info.title': 'Important Information',
        'reserves.info.checkin': 'Check-in: 3:00 PM | Check-out: 12:00 PM',
        'reserves.info.capacity': 'Room capacity: 12 people (+ camping option)',
        'reserves.info.pet': 'Pet friendly (with prior notice)',
        'reserves.info.party': 'No loud parties allowed',
        'reserves.questions.title': 'Questions?',
        'reserves.questions.text': 'If you have specific questions or special requirements, write to us directly.',
        'reserves.questions.chat': 'Chat via WhatsApp',
        // Footer
        'footer.desc': 'A natural refuge to disconnect and reconnect. Located in Silvania, Vereda Usatama Baja, Cundinamarca, where nature and rest meet.',
        'footer.nav.title': 'Navigation',
        'footer.contact.title': 'Contact',
        'footer.rights': 'Hacienda La Herrería. All rights reserved.',
        'footer.privacy': 'Privacy Policy',
        'footer.cookies': 'Cookie Policy',
        'footer.terms': 'Terms and Conditions',
        'booking.policy_agree': 'I accept the Privacy Policy and the processing of my personal data',
        // Auth
        'auth.login.title': 'Log In',
        'auth.login.noaccount': "Don't have an account?",
        'auth.login.register': 'Sign up here',
        'auth.email': 'Email',
        'auth.email.placeholder': 'Email',
        'auth.password': 'Password',
        'auth.password.placeholder': 'Password',
        'auth.submit.login': 'Log In',
        'auth.register.title': 'Create Account',
        'auth.register.hasaccount': 'Already have an account?',
        'auth.register.login': 'Log in',
        'auth.name': 'Full Name',
        'auth.name.placeholder': 'Full Name',
        'auth.submit.register': 'Sign Up',
        // Password Recovery
        'auth.forgot': 'Forgot your password?',
        'auth.recover.title': 'Recover Password',
        'auth.recover.desc': 'Enter your email to receive a recovery link.',
        'auth.recover.submit': 'Send Link',
        'auth.recover.success': 'Check your email for the recovery link.',
        'auth.recover.back': 'Back to Login',
        'auth.update.title': 'Update Password',
        'auth.update.submit': 'Update Password',
        'auth.update.success': 'Password updated successfully.',
        // Navbar Auth
        'nav.welcome': 'Welcome',
        'nav.logout': 'Log Out',
        // Experience Page
        'experience.label': 'The Experience',
        'experience.title': 'A sanctuary of well-being',
        'experience.intro': 'We have designed every aspect of your stay to ensure privacy, security, and tranquility.',
        'experience.philosophy.title': 'Rest Philosophy',
        'experience.philosophy.text': 'La Herrería is the ideal place to disconnect and vibrate in harmony with nature. Here you fully enjoy its deep connection with the elements—fertile earth, crystalline waters, gentle winds, and vital fire—while sharing energy with horses and curious cats, recharging yourself with peace and natural vitality.',
        'experience.noise.title': 'Zero Noise',
        'experience.noise.desc': 'Environment free of speakers and loud music.',
        'experience.privacy.title': 'Total Privacy',
        'experience.privacy.desc': 'Exclusive access for registered guests.',
        'experience.service.title': 'Personalized Service',
        'experience.service.text': 'Our host lives in an independent area within the property, ensuring a discreet presence but available for any need you may have.',
        'experience.service.list1': 'Personalized reception and welcome',
        'experience.service.list2': 'Assistance with bonfires and fireplaces',
        'experience.service.list3': 'Local recommendations',
        'experience.notes.title': 'Notes for your visit',
        'experience.notes.list2': 'No access to basements or restricted service areas.',
        'experience.notes.list3': 'Prior registration required for all companions.',
        'experience.notes.list4': 'Pets welcome with prior registration.',
        // Activities Page
        'activities.label': 'What to do',
        'activities.title': 'Activities and Surroundings',
        'activities.intro': 'From quiet contemplation to active adventure, La Herrería offers options for everyone.',
        'activities.item1.title': 'Ecological Walks',
        'activities.item1.desc': 'Walk natural trails inside and outside the hacienda. Discover local flora and breathe fresh air.',
        'activities.item2.title': 'Mountain Biking',
        'activities.item2.desc': 'Challenging and scenic routes for MTB lovers in the surroundings of Silvania.',
        'activities.item3.title': 'BBQ Areas',
        'activities.item3.desc': 'Spaces arranged to share a family barbecue surrounded by nature.',
        'activities.item4.title': 'Private Events',
        'activities.item4.desc': 'The perfect setting for family gatherings, small retreats, or intimate celebrations.',
        'activities.item5.title': 'Camping',
        'activities.item5.desc': 'Designated area for camping under the stars surrounded by safe nature.',
        'activities.item6.title': 'Soccer Field (Natural Grass)',
        'activities.item6.desc': 'Natural grass sports space to enjoy with friends and family.',
        'activities.item7.title': 'Tejo',
        'activities.item7.desc': 'Courts to play the traditional Colombian sport, ideal for groups.',
        'activities.item8.title': 'Rana',
        'activities.item8.desc': 'Frog game (Rana) available for entertainment and healthy competition.',
        'activities.cta.title': 'Ready to live the experience?',
        'activities.cta.text': 'Book now and secure your space in this natural refuge.',
        'activities.cta.button': 'Check Availability',
    }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('es');

    const t = (key: string) => {
        return translations[language][key as keyof typeof translations['es']] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
